# configuration file for dotnet-releaser
profile = "custom"
[msbuild]https://docs.github.com/ru/actions/security-guides/encrypted-secrets
project = "ReleaseNotes.sln"
[github]
user = "AntonyNET"
repo = "DotnetReleaserDemo"
[test]
enable = false
[coverage]
enable = false
[coveralls]
publish = false
[nuget]
publish = false
[brew]
publish = false
[scoop]
publish = false
[[pack]]
publish = false